name: Python Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Or specify a particular version like '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If you have a requirements.txt file, uncomment the following line:
        # pip install -r Backend/requirements.txt
      
    - name: Run pytest
      run: pytest
      working-directory: ./Backend